/* eslint-disable @next/next/no-img-element */
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/d0Cb0DFh07E
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { Chivo } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { CardContent, Card } from "@/components/ui/card";

export function HomePage() {
  return (
    <main className="flex-1">
      <section className="bg-base-200 py-12 md:py-20">
        <div className="container mx-auto px-4 md:px-8">
          <div className="grid md:grid-cols-2 gap-8 items-center ">
            <div>
              <h2 className="text-4xl font-bold mb-4 text-primary">
                Construyendo el futuro,
                <br />
                Pieza por pieza
              </h2>
              <p className="text-base-content text-lg mb-6">
                Sistemas H G C es el proveedor líder de piezas automotrices de
                alta calidad, que sirve a la industria automotriz desde hace más
                de dos décadas con experiencia e innovación.
              </p>
              <div className="flex items-center gap-4">
                <Link
                  className="btn btn-secondary hover:scale-105"
                  href="/contacto"
                >
                  Contacto
                </Link>
                <Link
                  className="btn glass  hover:scale-105"
                  href="/sobre-nosotros"
                >
                  Más Información
                </Link>
              </div>
            </div>
            <div className="hidden md:block">
              <img
                alt="Automotive Parts"
                className="rounded-lg shadow-md"
                height="400"
                src="../../images/homeimage.png"
                style={{
                  aspectRatio: "500/400",
                  objectFit: "cover",
                }}
                width="500"
              />
            </div>
          </div>
        </div>
      </section>
      <section className="py-12 md:py-20">
        <div className="container mx-auto px-4 md:px-8">
          <h2 className="text-3xl font-bold mb-8 text-center text-primary">
            Nuestros Clientes
          </h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            <a
              href="https://www.fiat.com.ar/"
              target="_blank"
              rel="noreferrer"
              className="btn btn-ghost glass hover:scale-105 max-w-[140px] h-20"
            >
              {" "}
              <img
                alt="Fiat"
                className="aspect-[2/1] object-contain"
                height="70"
                src="../../fiat-logo.png"
                width="140"
              />
            </a>
            <a
              href="https://www.renault.com.ar/"
              target="_blank"
              rel="noreferrer"
              className="btn btn-ghost glass hover:scale-105 max-w-[140px] h-20"
            >
              <img
                alt="Renault"
                className="aspect-[2/1] object-contain"
                height="70"
                src="../../Renault_2021.png"
                width="140"
              />
            </a>
            <img
              alt="Volkswagen"
              className="aspect-[2/1] object-contain"
              height="70"
              src="/placeholder.svg"
              width="140"
            />
            <img
              alt="Ford"
              className="aspect-[2/1] object-contain"
              height="70"
              src="/placeholder.svg"
              width="140"
            />
          </div>
        </div>
      </section>
      <section className="bg-base-200 py-12 md:py-20">
        <div className="container mx-auto px-4 md:px-8">
          <h2 className="text-3xl font-bold mb-8 text-center text-primary">
            Nuestros Productos
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <Card className="border-0">
              {/* <img
                alt="Apoya-Cabezas"
                className="rounded-t-lg"
                height="300"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width="400"
              /> */}
              <CardContent className="p-6 bg-primary rounded-lg">
                <h3 className="text-xl font-bold mb-2 text-base-100">
                  Apoya Cabezas
                </h3>
                <p className="text-base-200 mb-4">
                  Nuestros apoya-cabezas están diseñados para proporcionar el
                  máximo confort y seguridad durante sus viajes.
                </p>
              </CardContent>
            </Card>
            <Card className="border-0">
              {/* <img
                alt="Estructuras"
                className="rounded-t-lg"
                height="300"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width="400"
              /> */}
              <CardContent className="p-6 bg-primary rounded-lg">
                <h3 className="text-xl font-bold mb-2 text-base-100">
                  Estructuras
                </h3>
                <p className="text-base-200 mb-4">
                  Ofrecemos estructuras robustas y duraderas, ideales para la
                  construcción de vehículos resistentes y seguros.
                </p>
              </CardContent>
            </Card>
            <Card className="border-0">
              {/* <img
                alt="Parrillas"
                className="rounded-t-lg"
                height="300"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width="400"
              /> */}
              <CardContent className="p-6 bg-primary rounded-lg">
                <h3 className="text-xl font-bold mb-2 text-base-100">
                  Parrillas
                </h3>
                <p className="text-base-200 mb-4">
                  Nuestras parrillas ofrecen un diseño elegante y funcional,
                  proporcionando ventilación y protección al motor.
                </p>
              </CardContent>
            </Card>
            <Card className="border-0">
              {/* <img
                alt="Apoya-Brazos"
                className="rounded-t-lg"
                height="300"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width="400"
              /> */}
              <CardContent className="p-6 bg-primary rounded-lg">
                <h3 className="text-xl font-bold mb-2 text-base-100">
                  Apoya Brazos
                </h3>
                <p className="text-base-200 mb-4">
                  Diseñados para el confort del conductor y los pasajeros,
                  nuestros apoya-brazos son ergonómicos y ajustables.
                </p>
              </CardContent>
            </Card>
            <Card className="border-0">
              {/* <img
                alt="Respaldo"
                className="rounded-t-lg"
                height="300"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width="400"
              /> */}
              <CardContent className="p-6 bg-primary rounded-lg">
                <h3 className="text-xl font-bold mb-2 text-base-100">
                  Respaldo
                </h3>
                <p className="text-base-200 mb-4">
                  Nuestros respaldos ofrecen el soporte necesario para la
                  espalda, proporcionando una postura adecuada durante la
                  conducción.
                </p>
              </CardContent>
            </Card>
            <Card className="border-0">
              {/* <img
                alt="Soportes"
                className="rounded-t-lg"
                height="300"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width="400"
              /> */}
              <CardContent className="p-6 bg-primary rounded-lg">
                <h3 className="text-xl font-bold mb-2 text-base-100">
                  Soportes
                </h3>
                <p className="text-base-200 mb-4">
                  Ofrecemos una variedad de soportes diseñados para diferentes
                  aplicaciones automotrices, garantizando estabilidad y
                  seguridad.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      <section className="bg-primary text-base-100 py-12 md:py-20">
        <div className="container mx-auto px-4 md:px-8">
          <div className="grid md:grid-cols-2 gap-8 items-center">
            <div>
              <h2 className="text-3xl font-bold mb-4">
                Contáctanos para más información
              </h2>
              <p className="text-gray-400 mb-6">
                Estamos aquí para ayudarte con tus necesidades de piezas
                automotrices. Llámanos o envíanos un mensaje.
              </p>
              <div className="flex items-center gap-4">
                <Link
                  className="btn btn-secondary hover:scale-105"
                  href="/contacto"
                >
                  Enviar Mensaje
                </Link>
                <a
                  className="text-base-100 hover:underline flex items-center gap-2"
                  href="tel:+541147220988"
                >
                  <PhoneIcon className="h-5 w-5" />
                  11 4722-0988
                </a>
              </div>
            </div>
            <div className="hidden md:block">
              <img
                alt="Contact Us"
                className="rounded-lg"
                height="400"
                src="../../images/sistemas-hgc-taller.png"
                style={{
                  aspectRatio: "500/400",
                  objectFit: "cover",
                }}
                width="500"
              />
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}

function PhoneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  );
}
