/* eslint-disable @next/next/no-img-element */
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lONKrLUHwzo
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Crimson_Text } from 'next/font/google'
import { Caudex } from 'next/font/google'

crimson_text({
  subsets: ['latin'],
  display: 'swap',
})

caudex({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";

export function SobreNosotros() {
  return (
    <div className="bg-base-100 text-gray-900 dark:bg-gray-950 dark:text-gray-50">
      <header className="bg-gradient-to-r from-primary to-secondary py-16 md:py-24 lg:py-32">
        <div className="container mx-auto px-4 md:px-6 lg:px-8">
          <div className="max-w-3xl text-center mx-auto">
            <h1 className="text-5xl font-bold tracking-tight text-base-100 sm:text-6xl md:text-7xl">
              Sistemas H G C
            </h1>
            <p className="mt-8 text-xl leading-8 text-base-100">
              Expertos en fabricación y comercialización de piezas automotrices
              con más de 10 años de experiencia.
            </p>
          </div>
        </div>
      </header>
      <section className="py-16 md:py-24 lg:py-32">
        <div className="container mx-auto px-4 md:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12 md:gap-16 lg:gap-20">
            <div>
              <h2 className="text-4xl font-bold tracking-tight text-primary sm:text-5xl md:text-6xl">
                Nuestra Historia
              </h2>
              <p className="mt-8 text-lg leading-8 text-gray-600">
                Sistemas H G C fue fundada en 2010 con el objetivo de
                proporcionar soluciones innovadoras y de alta calidad para la
                industria automotriz. Desde entonces, hemos crecido
                constantemente, convirtiéndonos en un proveedor confiable y
                respetado en el mercado.
              </p>
            </div>
            <div>
              <h2 className="text-4xl font-bold tracking-tight text-primary sm:text-5xl md:text-6xl">
                Misión y Valores
              </h2>
              <p className="mt-8 text-lg leading-8 text-gray-600">
                Nuestra misión es ser líderes en la fabricación y
                comercialización de piezas automotrices, ofreciendo productos de
                alta calidad y un servicio excepcional a nuestros clientes.
                Nuestros valores de integridad, innovación y excelencia
                operativa guían todas nuestras acciones.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="py-16 md:py-24 lg:py-32 bg-neutral dark:bg-gray-800">
        <div className="container mx-auto px-4 md:px-6 lg:px-8">
          <h2 className="text-4xl font-bold tracking-tight text-primary sm:text-5xl md:text-6xl text-center">
            Nuestra Experiencia
          </h2>
          <p className="mt-8 text-lg leading-8 text-gray-600 text-center max-w-2xl mx-auto">
            Sistemas H G C es una empresa líder en la fabricación y
            comercialización de piezas automotrices. Con más de una década de
            experiencia en el sector, hemos desarrollado un profundo
            conocimiento de las necesidades de nuestros clientes y una capacidad
            probada para entregar soluciones a la medida.
          </p>
          <div className="mt-16 grid grid-cols-2 md:grid-cols-4 gap-12 md:gap-16 lg:gap-20">
            <div className="flex justify-center">
              <img
                alt="Fiat"
                className="h-14 w-auto"
                height={60}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "120/60",
                  objectFit: "cover",
                }}
                width={120}
              />
            </div>
            <div className="flex justify-center">
              <img
                alt="Renault"
                className="h-14 w-auto"
                height={60}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "120/60",
                  objectFit: "cover",
                }}
                width={120}
              />
            </div>
            <div className="flex justify-center">
              <img
                alt="Logo"
                className="h-14 w-auto"
                height={60}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "120/60",
                  objectFit: "cover",
                }}
                width={120}
              />
            </div>
            <div className="flex justify-center">
              <img
                alt="Logo"
                className="h-14 w-auto"
                height={60}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "120/60",
                  objectFit: "cover",
                }}
                width={120}
              />
            </div>
          </div>
        </div>
      </section>
      <section className="py-16 md:py-24 lg:py-32">
        <div className="container mx-auto px-4 md:px-6 lg:px-8">
          <h2 className="text-4xl font-bold tracking-tight text-primary sm:text-5xl md:text-6xl text-center">
            Nuestro Equipo
          </h2>
          <p className="mt-8 text-lg leading-8 text-gray-600 text-center max-w-2xl mx-auto">
            Nuestro equipo está compuesto por expertos en la industria
            automotriz, comprometidos con brindar soluciones innovadoras y un
            servicio excepcional a nuestros clientes.
          </p>
          <div className="mt-16 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-12 md:gap-16 lg:gap-20">
            <div className="flex flex-col items-center">
              <img
                alt="John Doe"
                className="rounded-full w-40 h-40 object-cover"
                height={160}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "160/160",
                  objectFit: "cover",
                }}
                width={160}
              />
              <h3 className="mt-6 text-2xl font-bold text-primary">John Doe</h3>
              <p className="mt-2 text-gray-500 dark:text-gray-400">
                CEO y Fundador
              </p>
            </div>
            <div className="flex flex-col items-center">
              <img
                alt="Jane Smith"
                className="rounded-full w-40 h-40 object-cover"
                height={160}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "160/160",
                  objectFit: "cover",
                }}
                width={160}
              />
              <h3 className="mt-6 text-2xl font-bold text-primary">
                Jane Smith
              </h3>
              <p className="mt-2 text-gray-500 dark:text-gray-400">
                Gerente de Producción
              </p>
            </div>
            <div className="flex flex-col items-center">
              <img
                alt="Bob Johnson"
                className="rounded-full w-40 h-40 object-cover"
                height={160}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "160/160",
                  objectFit: "cover",
                }}
                width={160}
              />
              <h3 className="mt-6 text-2xl font-bold text-primary">
                Bob Johnson
              </h3>
              <p className="mt-2 text-gray-500 dark:text-gray-400">
                Director de Ventas
              </p>
            </div>
            <div className="flex flex-col items-center">
              <img
                alt="Sarah Lee"
                className="rounded-full w-40 h-40 object-cover"
                height={160}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "160/160",
                  objectFit: "cover",
                }}
                width={160}
              />
              <h3 className="mt-6 text-2xl font-bold text-primary">
                Sarah Lee
              </h3>
              <p className="mt-2 text-gray-500 dark:text-gray-400">
                Gerente de Calidad
              </p>
            </div>
          </div>
        </div>
      </section>
      <footer className="bg-neutral dark:bg-gray-800 py-8 md:py-10 lg:py-12">
        <div className="container mx-auto px-4 md:px-6 lg:px-8 flex flex-col md:flex-row items-center justify-between">
          <p className="text-gray-500 dark:text-gray-400 text-sm">
            © 2024 Sistemas H G C. Todos los derechos reservados.
          </p>
          <div className="flex space-x-4 mt-4 md:mt-0">
            <Link
              className="text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-50 text-sm"
              href="#"
            >
              Inicio
            </Link>
            <Link
              className="text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-50 text-sm"
              href="#"
            >
              Contacto
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
